package com.roshan.know_base.common.enums;

public enum ErrorCode {
    NOT_FOUND,
    INVALID_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    ACCESS_DENIED,
    INVALID_ROLE,
    INVALID_CREDENTIAL,
    ALREADY_EXISTS,
    REFRESH_TOKEN_MISSING,
    DOCUMENT_PROCESSING_FAILED,
    DOCUMENT_STORAGE_ERROR
}
